"""Step 5e: validate sparse edge-aligned BEM panel budgets.

This workflow still does not solve BEM. It compares the panel counts of
the previous full-grid edge-aligned builder and the sparse L1 builder,
while verifying that inner and outer RF boundary changes remain visible.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import matplotlib.pyplot as plt
import numpy as np

from config.targets import TARGET_ION_HEIGHT_M
from core.geometry.junction_templates import make_house_style_x_junction
from core.geometry.mask_builder import (
    build_sparse_x_junction_bem,
    build_x_junction_bem,
)

if TYPE_CHECKING:
    from core.geometry.mask_builder import XJunctionBEMModel


def plot_sparse_masks(
    models: list[tuple[str, "XJunctionBEMModel"]],
    *,
    output_path: Path,
) -> None:
    """Plot RF masks generated by sparse edge-aligned configurations."""
    figure, axes = plt.subplots(
        1,
        len(models),
        figsize=(5.0 * len(models), 4.8),
        sharex=True,
        sharey=True,
    )

    if len(models) == 1:
        axes = [axes]

    image = None

    for axis, (label, model) in zip(axes, models):
        image = axis.pcolormesh(
            model.x_edges_m * 1e6,
            model.y_edges_m * 1e6,
            model.rf_mask.astype(float),
            shading="flat",
            cmap="RdYlBu_r",
            vmin=0.0,
            vmax=1.0,
        )

        axis.set_aspect("equal")
        axis.set_xlim(-250.0, 250.0)
        axis.set_ylim(-250.0, 250.0)
        axis.set_xlabel("x [um]")
        axis.set_ylabel("y [um]")
        axis.set_title(
            f"{label}\nN={model.n_panels} panels"
        )

    if image is not None:
        colorbar = figure.colorbar(
            image,
            ax=list(axes),
            shrink=0.78,
        )
        colorbar.set_ticks([0.0, 1.0])
        colorbar.set_ticklabels(["Ground", "RF"])

    figure.subplots_adjust(
        left=0.06,
        right=0.91,
        bottom=0.12,
        top=0.86,
        wspace=0.18,
    )
    figure.suptitle("Sparse edge-aligned L1 meshes")
    figure.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close(figure)


def main() -> None:
    output_directory = Path("reports") / "figures" / "05e_sparse_mesh"
    output_directory.mkdir(parents=True, exist_ok=True)

    candidates = [
        ("baseline", 0.0, 0.0),
        ("outer +20 um", 0.0, 20e-6),
        ("outer +40 um", 0.0, 40e-6),
    ]

    sparse_models: list[tuple[str, XJunctionBEMModel]] = []

    print("Sparse edge-aligned mesh validation")
    print("-" * 112)
    print(
        f"{'candidate':<20} "
        f"{'full-grid N':>14} {'sparse N':>12} "
        f"{'reduction':>12} {'sparse RF cells':>18}"
    )

    for label, inner_shift_m, outer_shift_m in candidates:
        parameters = make_house_style_x_junction(
            ion_height_m=TARGET_ION_HEIGHT_M,
            arm_length_m=600e-6,
            outer_extent_m=900e-6,
            taper_length_m=150e-6,
            inner_edge_shift_at_centre_m=inner_shift_m,
            outer_edge_shift_at_centre_m=outer_shift_m,
            taper_power=2.0,
        )

        full_model = build_x_junction_bem(
            parameters,
            edge_aligned=True,
            n_longitudinal_samples=13,
            max_cell_size_centre_m=18e-6,
            max_cell_size_outer_m=90e-6,
            centre_refinement_radius_m=220e-6,
        )

        sparse_model = build_sparse_x_junction_bem(
            parameters,
            n_longitudinal_samples=13,
            central_half_extent_m=180e-6,
            central_cell_size_m=25e-6,
            transition_cell_size_m=70e-6,
            outer_cell_size_m=220e-6,
        )
        sparse_models.append((label, sparse_model))

        reduction = full_model.n_panels / sparse_model.n_panels

        print(
            f"{label:<20} "
            f"{full_model.n_panels:14d} "
            f"{sparse_model.n_panels:12d} "
            f"{reduction:12.2f}x "
            f"{int(np.sum(sparse_model.rf_mask)):18d}"
        )

    plot_sparse_masks(
        sparse_models,
        output_path=output_directory / "sparse_edge_aligned_masks.png",
    )

    print()
    print(
        "The sparse builder is acceptable for repeated dense-BEM screening "
        "only if panel counts are comfortably below roughly 2000 panels."
    )
    print(
        f"Figure saved to: "
        f"{output_directory / 'sparse_edge_aligned_masks.png'}"
    )


if __name__ == "__main__":
    main()