"""Open-centre C4v X-junction search with piecewise-linear inner/outer RF edges.

This is a complete replacement workflow. It deliberately uses a free, locally
piecewise-linear genome for both RF boundaries (not polynomials). Four copies
of one fundamental contour are generated by the project C4v template. No
central RF cross is inserted.

Discovery: nondominated NSGA-II on (peak |z-z_target|, RF barrier).
Certification: only fine mesh + complete trace + dz < 3 um and barrier < 1 meV.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle
from tqdm.auto import tqdm

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config.targets import RF_ANGULAR_FREQUENCY_RAD_S, TARGET_ION_HEIGHT_M
from core.analysis.barrier import compute_barrier_metrics, pseudopotential_profile_ev
from core.analysis.rf_null_trace import trace_rf_transverse_minimum
from core.ga.fixed_bem import FixedMeshBEM, available_backend
from core.geometry.junction_templates import make_house_style_x_junction
from core.geometry.manufacturability import check_x_junction_manufacturability
from core.geometry.mask_builder import build_geometry_aware_quadtree_x_junction_bem

# Boundary coordinates on one C4v fundamental arm. The first / last values
# are fixed to zero offsets; all interior values are independently mutable.
KNOTS_M = np.array([0, 5, 10, 15, 20, 30, 45, 60, 90, 120, 150, 210], dtype=float) * 1e-6
N_EDGE = len(KNOTS_M) - 2
INNER = slice(0, N_EDGE)
OUTER = slice(N_EDGE, 2 * N_EDGE)
CENTER_IN, CENTER_OUT, START, LENGTH, POWER, BULGE, BULGE_CENTER, BULGE_WIDTH = range(2 * N_EDGE, 2 * N_EDGE + 8)
N_GENES = 2 * N_EDGE + 8

# [inner knot offsets | outer knot offsets | central/global geometry]
LOW = np.array([-35e-6] * (2 * N_EDGE) + [-50e-6, -8e-6, 5e-6, 55e-6, .65, -35e-6, 8e-6, 6e-6])
HIGH = np.array([35e-6] * (2 * N_EDGE) + [-3e-6, 65e-6, 60e-6, 330e-6, 5.5, 35e-6, 145e-6, 85e-6])


@dataclass(frozen=True)
class Settings:
    backend: str
    islands: int
    population: int
    offspring: int
    generations: int
    migration_interval: int
    migrants: int
    checkpoint_interval: int
    seed: int
    coarse_points: int
    fine_points: int
    fine_top: int
    max_panels: int
    fast: bool
    output_dir: Path
    rf_peak_v: float = 100.0
    target_z_m: float = TARGET_ION_HEIGHT_M
    dz_limit_m: float = 3e-6
    barrier_limit_ev: float = 1e-3
    lateral_limit_m: float = 5e-6


@dataclass(frozen=True)
class IslandStyle:
    name: str
    objective_weights: tuple[float, float]
    initial_sigma: float
    mutation_sigma: float
    emphasis: str


STYLES = (
    IslandStyle("height", (6.0, 1.0), .38, .19, "inner"),
    IslandStyle("barrier", (1.0, 6.0), .38, .19, "outer"),
    IslandStyle("central", (2.0, 2.0), .44, .23, "central"),
    IslandStyle("coupled", (2.0, 2.0), .36, .18, "both"),
    IslandStyle("local", (2.0, 2.0), .11, .040, "local"),
    IslandStyle("restart", (2.0, 2.0), .55, .28, "both"),
)


@dataclass
class Individual:
    genome: np.ndarray
    result: dict[str, Any]
    island: int
    generation: int
    origin: str
    rank: int = 0
    crowding: float = 0.0

    @property
    def valid(self) -> bool:
        return bool(self.result["valid"])

    @property
    def objective(self) -> np.ndarray:
        if not self.valid:
            return np.array([np.inf, np.inf])
        return np.array([self.result["dz_peak_m"] / 3e-6,
                         self.result["barrier_ev"] / 1e-3], dtype=float)

    def copy(self) -> "Individual":
        return Individual(self.genome.copy(), dict(self.result), self.island,
                          self.generation, self.origin, self.rank, self.crowding)


@dataclass
class Island:
    style: IslandStyle
    rng: np.random.Generator
    population: list[Individual]


class BEMField:
    def __init__(self, bem: FixedMeshBEM, charge: Any):
        self.bem = bem
        self.charge = charge

    def electric_field(self, x_m: float, y_m: float, z_m: float):
        field = self.bem.field_batch(np.array([x_m]), np.array([y_m]),
                                     np.array([z_m]), self.charge)
        return tuple(map(float, self.bem.asnumpy(field)[0, 0]))


def repair(genome: np.ndarray) -> np.ndarray:
    """Clip values and reject only mesh-aliasing / near-vertical edge artifacts.

    The result remains piecewise-linear. This does not smooth or spline the
    contour; it merely bounds slope so a feature spans more than one mesh cell.
    """
    x = np.asarray(genome, dtype=float).copy()
    if x.shape != (N_GENES,) or not np.all(np.isfinite(x)):
        raise ValueError(f"Genome must contain {N_GENES} finite values")
    x = np.clip(x, LOW, HIGH)
    max_abs_slope = 1.25
    for edge in (INNER, OUTER):
        values = np.r_[0.0, x[edge], 0.0]
        for _ in range(4):
            for i in range(1, len(values)):
                limit = max_abs_slope * (KNOTS_M[i] - KNOTS_M[i-1])
                values[i] = np.clip(values[i], values[i-1]-limit, values[i-1]+limit)
            for i in range(len(values)-2, -1, -1):
                limit = max_abs_slope * (KNOTS_M[i+1] - KNOTS_M[i])
                values[i] = np.clip(values[i], values[i+1]-limit, values[i+1]+limit)
        x[edge] = values[1:-1]
    return x


def baseline() -> np.ndarray:
    x = np.zeros(N_GENES)
    x[CENTER_IN:] = [-25e-6, 20e-6, 30e-6, 150e-6, 2.0, 0.0, 70e-6, 25e-6]
    return x


def seed_genomes() -> list[tuple[str, np.ndarray]]:
    base = baseline()
    h = base.copy()
    h[[6, 7, 8]] = [-12e-6, -12e-6, -9e-6]
    b = base.copy()
    b[[6, 7, 8]] = [-12e-6, -8e-6, -9e-6]
    both = base.copy()
    both[[4, 5, 6, 7, 8]] = [-8e-6, -15e-6, -18e-6, -13e-6, -7e-6]
    both[N_EDGE + np.array([4, 5, 6, 7, 8])] = [5e-6, 10e-6, 13e-6, 9e-6, 4e-6]
    return [("baseline", base), ("height_seed", h), ("barrier_seed", b),
            ("coupled_piecewise_seed", both)]


def make_parameters(x: np.ndarray):
    return make_house_style_x_junction(
        ion_height_m=TARGET_ION_HEIGHT_M,
        arm_length_m=600e-6,
        outer_extent_m=900e-6,
        inner_edge_shift_at_centre_m=float(x[CENTER_IN]),
        outer_edge_shift_at_centre_m=float(x[CENTER_OUT]),
        rf_start_radius_override_m=float(x[START]),
        taper_length_m=float(x[LENGTH]),
        taper_power=float(x[POWER]),
        outer_bulge_amplitude_m=float(x[BULGE]),
        outer_bulge_center_m=float(x[BULGE_CENTER]),
        outer_bulge_sigma_m=float(x[BULGE_WIDTH]),
        inner_contour_knots_m=tuple(KNOTS_M),
        inner_contour_offsets_m=tuple(np.r_[0.0, x[INNER], 0.0]),
        outer_contour_knots_m=tuple(np.r_[0.0, x[OUTER], 0.0]),
    )


def reject(reason: str, stage: str) -> dict[str, Any]:
    return dict(valid=False, verified=False, reason=reason, stage=stage,
                dz_peak_m=np.inf, dz_rms_m=np.inf, barrier_ev=np.inf,
                lateral_peak_m=np.inf, panels=0, points=0, converged=0)


def build_mesh(parameters: Any, fast: bool):
    if fast:
        return build_geometry_aware_quadtree_x_junction_bem(
            parameters, central_half_extent_m=145e-6, central_max_cell_m=46e-6,
            boundary_max_cell_m=17e-6, outer_max_cell_m=180e-6, min_cell_m=8e-6)
    return build_geometry_aware_quadtree_x_junction_bem(
        parameters, central_half_extent_m=180e-6, central_max_cell_m=30e-6,
        boundary_max_cell_m=10e-6, outer_max_cell_m=180e-6, min_cell_m=5e-6)


def evaluate(genome: np.ndarray, cfg: Settings, stage="coarse", retain=False):
    x = repair(genome)
    try:
        p = make_parameters(x)
        mfg = check_x_junction_manufacturability(p)
        if not mfg.valid:
            return reject("geometry: " + "; ".join(map(str, mfg.messages)), stage), None
        s = np.linspace(0, p.arm_length_m, 2001)
        r_in, r_out = p.rail_boundaries_m(s)
        width = r_out - r_in
        if np.min(r_in) <= 0.5e-6:
            return reject("inner edge enters central clearance", stage), None
        if np.min(width) < 18e-6:
            return reject("RF rail narrower than 18 um", stage), None
        model = build_mesh(p, cfg.fast and stage == "coarse")
        if model.n_panels > cfg.max_panels:
            return reject(f"panel limit {model.n_panels}>{cfg.max_panels}", stage), None
        bem = FixedMeshBEM(model.bem.panels_m, backend=cfg.backend)
        bem.assemble(block_rows=64)
        bem.factorize()
        bem.release_matrix()
        charge = bem.solve_masks(model.bem.electrode_voltages_v)
        field = BEMField(bem, charge)
        count = cfg.fine_points if stage == "fine" else cfg.coarse_points
        xs = np.linspace(-350e-6, 350e-6, count)
        trace = trace_rf_transverse_minimum(
            field, xs, initial_y_m=0.0, initial_z_m=cfg.target_z_m,
            residual_tolerance_v_m=1e-3, max_transverse_shift_m=25e-6)
        converged = np.asarray(trace.converged, dtype=bool)
        z = np.asarray(trace.z_m, dtype=float)
        y = np.asarray(trace.y_m, dtype=float)
        if not trace.valid or converged.shape != (count,) or not np.all(converged):
            return reject(f"incomplete trace {int(np.sum(converged))}/{count}", stage), None
        if not np.all(np.isfinite(z)) or not np.all(np.isfinite(y)):
            return reject("nonfinite null trace", stage), None
        potential = np.asarray(pseudopotential_profile_ev(
            field, trace, rf_voltage_peak_v=cfg.rf_peak_v,
            rf_angular_frequency_rad_s=RF_ANGULAR_FREQUENCY_RAD_S), dtype=float)
        barrier = compute_barrier_metrics(potential, trace)
        if not barrier.valid or potential.shape != (count,) or not np.all(np.isfinite(potential)):
            return reject("invalid pseudopotential profile", stage), None
        dz = z - cfg.target_z_m
        dz_peak = float(np.max(np.abs(dz)))
        dz_rms = float(np.sqrt(np.mean(dz**2)))
        lateral_peak = float(np.max(np.abs(y)))
        barrier_ev = float(barrier.barrier_height_ev)
        if not np.all(np.isfinite([dz_peak, dz_rms, lateral_peak, barrier_ev])):
            return reject("nonfinite physical metric", stage), None
        result = dict(
            valid=True,
            verified=bool(stage == "fine" and dz_peak < cfg.dz_limit_m
                          and barrier_ev < cfg.barrier_limit_ev
                          and lateral_peak < cfg.lateral_limit_m),
            reason="ok", stage=stage, backend=bem.backend_name,
            dz_peak_m=dz_peak, dz_rms_m=dz_rms, barrier_ev=barrier_ev,
            lateral_peak_m=lateral_peak,
            barrier_reference_ev=float(barrier.reference_energy_ev),
            panels=int(model.n_panels), points=count, converged=int(np.sum(converged)))
        return result, (model, trace, potential) if retain else None
    except Exception as error:
        if cfg.backend == "cuda" and "out of memory" in str(error).lower():
            raise RuntimeError("CUDA OOM: reduce --max-panels or use --fast") from error
        return reject(f"{type(error).__name__}: {error}", stage), None


def dominates(a: Individual, b: Individual) -> bool:
    if a.valid != b.valid:
        return a.valid
    if not a.valid:
        return False
    return bool(np.all(a.objective <= b.objective) and np.any(a.objective < b.objective))


def rank_and_crowding(population: list[Individual]) -> list[list[int]]:
    count = len(population)
    dominates_set = [[] for _ in population]
    losses = np.zeros(count, dtype=int)
    fronts: list[list[int]] = [[]]
    for i in range(count):
        for j in range(i + 1, count):
            if dominates(population[i], population[j]):
                dominates_set[i].append(j)
                losses[j] += 1
            elif dominates(population[j], population[i]):
                dominates_set[j].append(i)
                losses[i] += 1
    fronts[0] = [i for i in range(count) if losses[i] == 0]
    while fronts[-1]:
        next_front: list[int] = []
        for i in fronts[-1]:
            for j in dominates_set[i]:
                losses[j] -= 1
                if losses[j] == 0:
                    next_front.append(j)
        fronts.append(next_front)
    fronts.pop()
    for level, front in enumerate(fronts):
        for i in front:
            population[i].rank = level
            population[i].crowding = 0.0
        valid = [i for i in front if population[i].valid]
        if len(valid) <= 2:
            for i in valid:
                population[i].crowding = np.inf
            continue
        for axis in range(2):
            order = sorted(valid, key=lambda i: population[i].objective[axis])
            low = population[order[0]].objective[axis]
            high = population[order[-1]].objective[axis]
            if high <= low:
                continue
            population[order[0]].crowding = np.inf
            population[order[-1]].crowding = np.inf
            for j in range(1, len(order) - 1):
                item = population[order[j]]
                if np.isfinite(item.crowding):
                    item.crowding += ((population[order[j+1]].objective[axis]
                                       - population[order[j-1]].objective[axis]) / (high - low))
    return fronts


def survive(pool: list[Individual], size: int) -> list[Individual]:
    fronts = rank_and_crowding(pool)
    output: list[Individual] = []
    for front in fronts:
        front.sort(key=lambda i: pool[i].crowding, reverse=True)
        output.extend(pool[i].copy() for i in front[:size-len(output)])
        if len(output) == size:
            return output
    return output


def style_score(item: Individual, style: IslandStyle) -> float:
    return np.inf if not item.valid else float(np.dot(style.objective_weights, item.objective))


def tournament(population: list[Individual], style: IslandStyle, rng: np.random.Generator) -> Individual:
    a, b = (population[int(i)] for i in rng.integers(0, len(population), 2))
    if rng.random() < .50:
        return a if style_score(a, style) < style_score(b, style) else b
    if a.rank != b.rank:
        return a if a.rank < b.rank else b
    if a.crowding != b.crowding:
        return a if a.crowding > b.crowding else b
    return a if style_score(a, style) < style_score(b, style) else b


def mutate(parent: np.ndarray, style: IslandStyle, rng: np.random.Generator, progress: float) -> np.ndarray:
    x = parent.copy()
    p = np.full(N_GENES, .58)
    if style.emphasis == "inner":
        p[INNER] = .92
    elif style.emphasis == "outer":
        p[OUTER] = .92
    elif style.emphasis == "central":
        p[:2*N_EDGE] = .80
        p[CENTER_IN:CENTER_OUT+1] = .95
    active = rng.random(N_GENES) < p
    scale = style.mutation_sigma * (1.0 - .60 * progress)
    x[active] += rng.normal(0.0, (HIGH-LOW)[active] * scale)
    # Coordinated but still piecewise-linear local kicks; not smoothing.
    shape = np.array([.28, .58, .90, 1.0, .86, .62, .38, .20, .09, .0])
    local_sigma = 15e-6 * (1.0 - .50 * progress)
    if style.emphasis in ("inner", "both", "central"):
        x[INNER] += rng.normal(0.0, local_sigma) * shape
    if style.emphasis in ("outer", "both", "central"):
        x[OUTER] += rng.normal(0.0, local_sigma) * shape
    return repair(x)


def record(individual: Individual) -> dict[str, Any]:
    return dict(island=individual.island, generation=individual.generation,
                origin=individual.origin, rank=individual.rank,
                crowding=individual.crowding, genome=individual.genome.tolist(),
                **individual.result)


def save_csv(rows: list[dict[str, Any]], filename: Path) -> None:
    filename.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        filename.write_text("", encoding="utf-8")
        return
    keys = sorted(set().union(*(row.keys() for row in rows)))
    with filename.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=keys, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: json.dumps(value, allow_nan=True)
                             if isinstance(value, (dict, list)) else value
                             for key, value in row.items()})


def draw_fine(data: tuple[Any, Any, np.ndarray], result: dict[str, Any], directory: Path) -> None:
    model, trace, potential = data
    panels = np.asarray(model.bem.panels_m)
    rf = np.asarray(model.bem.electrode_voltages_v) > .5
    rectangles = [Rectangle((p[0]*1e6, p[2]*1e6), (p[1]-p[0])*1e6, (p[3]-p[2])*1e6)
                  for p in panels]
    fig, ax = plt.subplots(figsize=(7, 7))
    collection = PatchCollection(rectangles, array=rf.astype(float), cmap="RdYlBu_r")
    ax.add_collection(collection)
    ax.plot(np.asarray(trace.x_m)*1e6, np.asarray(trace.y_m)*1e6, "k-", lw=1.3)
    ax.set(xlim=(-230, 230), ylim=(-230, 230), xlabel="x [um]", ylabel="y [um]",
           title="Open-centre C4v RF mask; piecewise-linear edge genome")
    ax.set_aspect("equal")
    fig.colorbar(collection, ax=ax)
    fig.tight_layout()
    fig.savefig(directory / "layout.png", dpi=170)
    plt.close(fig)
    x = np.asarray(trace.x_m) * 1e6
    fig, axes = plt.subplots(3, 1, figsize=(9, 9), sharex=True)
    axes[0].plot(x, (np.asarray(trace.z_m)-TARGET_ION_HEIGHT_M)*1e6)
    axes[0].axhline(3.0, color="r", ls="--"); axes[0].axhline(-3.0, color="r", ls="--")
    axes[0].set_ylabel("z-target [um]")
    axes[1].plot(x, (potential-result["barrier_reference_ev"])*1e3)
    axes[1].axhline(1.0, color="r", ls="--")
    axes[1].set_ylabel("RF pseudo - ref [meV]")
    axes[2].plot(x, np.asarray(trace.y_m)*1e6)
    axes[2].set_ylabel("y [um]"); axes[2].set_xlabel("x [um]")
    for ax in axes:
        ax.grid(alpha=.25)
    fig.tight_layout()
    fig.savefig(directory / "profiles.png", dpi=170)
    plt.close(fig)


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--backend", choices=("auto", "cuda", "cpu"), default="auto")
    p.add_argument("--islands", type=int, default=6)
    p.add_argument("--population", type=int, default=32)
    p.add_argument("--offspring", type=int, default=32)
    p.add_argument("--generations", type=int, default=80)
    p.add_argument("--migration-interval", type=int, default=4)
    p.add_argument("--migrants", type=int, default=2)
    p.add_argument("--checkpoint-interval", type=int, default=5)
    p.add_argument("--coarse-points", type=int, default=61)
    p.add_argument("--fine-points", type=int, default=181)
    p.add_argument("--fine-top", type=int, default=14)
    p.add_argument("--max-panels", type=int, default=7000)
    p.add_argument("--fast", action="store_true")
    p.add_argument("--seed", type=int, default=20260926)
    p.add_argument("--output-dir", type=Path, default=Path("reports/07_piecewise_c4v"))
    return p


def main() -> None:
    args = parser().parse_args()
    backend = available_backend(args.backend)
    if not backend.available:
        raise RuntimeError(backend.reason)
    if not 1 <= args.islands <= len(STYLES):
        raise ValueError(f"--islands must be 1..{len(STYLES)}")
    if args.population < 8 or min(args.offspring, args.generations, args.coarse_points,
                                  args.fine_points, args.max_panels) < 1:
        raise ValueError("population must be >=8 and all numerical options positive")
    cfg = Settings(backend.selected, args.islands, args.population, args.offspring,
                   args.generations, args.migration_interval, args.migrants,
                   args.checkpoint_interval, args.seed, args.coarse_points,
                   args.fine_points, args.fine_top, args.max_panels, args.fast,
                   args.output_dir)
    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    (cfg.output_dir / "settings.json").write_text(json.dumps(dict(
        backend=backend.as_dict(), knots_m=KNOTS_M.tolist(),
        rf_peak_v=cfg.rf_peak_v, rf_omega_rad_s=RF_ANGULAR_FREQUENCY_RAD_S,
        target_z_m=cfg.target_z_m, dz_limit_m=cfg.dz_limit_m,
        barrier_limit_ev=cfg.barrier_limit_ev, coarse_points=cfg.coarse_points,
        fine_points=cfg.fine_points, fast=cfg.fast), indent=2), encoding="utf-8")
    print("Piecewise-linear open-centre C4v island GA | backend:", backend.selected,
          "| device:", backend.device_name, flush=True)
    print("Discovery: Pareto(dz, barrier). Fine certification: dz<3 um AND barrier<1 meV.")

    master = np.random.default_rng(cfg.seed)
    seeds = seed_genomes()
    cache: dict[tuple[float, ...], dict[str, Any]] = {}
    best_z: tuple[np.ndarray, dict[str, Any]] | None = None
    best_u: tuple[np.ndarray, dict[str, Any]] | None = None
    best_joint: tuple[np.ndarray, dict[str, Any]] | None = None

    def live_postfix(bar: tqdm) -> None:
        if best_z is None or best_u is None:
            bar.set_postfix_str("waiting for valid trace", refresh=False)
            return
        entries = {
            "dz": f'{best_z[1]["dz_peak_m"]*1e6:.2f}um/U{best_z[1]["barrier_ev"]*1e3:.1f}',
            "U": f'{best_u[1]["barrier_ev"]*1e3:.2f}meV/dz{best_u[1]["dz_peak_m"]*1e6:.1f}',
        }
        if best_joint is not None:
            entries["joint"] = f'dz{best_joint[1]["dz_peak_m"]*1e6:.2f}/U{best_joint[1]["barrier_ev"]*1e3:.2f}'
        bar.set_postfix(entries, refresh=False)

    def coarse(x: np.ndarray, bar: tqdm | None = None) -> dict[str, Any]:
        nonlocal best_z, best_u, best_joint
        x = repair(x)
        key = tuple(np.round(x, 12))
        if key not in cache:
            cache[key], _ = evaluate(x, cfg, stage="coarse")
        result = dict(cache[key])
        changed = False
        if result["valid"]:
            if best_z is None or result["dz_peak_m"] < best_z[1]["dz_peak_m"]:
                best_z = (x.copy(), result.copy()); changed = True
            if best_u is None or result["barrier_ev"] < best_u[1]["barrier_ev"]:
                best_u = (x.copy(), result.copy()); changed = True
            joint_score = max(result["dz_peak_m"]/10e-6, result["barrier_ev"]/10e-3)
            if best_joint is None or joint_score < max(best_joint[1]["dz_peak_m"]/10e-6,
                                                       best_joint[1]["barrier_ev"]/10e-3):
                best_joint = (x.copy(), result.copy()); changed = True
        if changed and best_z is not None and best_u is not None and best_joint is not None:
            payload = dict(
                best_dz=dict(genome=best_z[0].tolist(), **best_z[1]),
                best_barrier=dict(genome=best_u[0].tolist(), **best_u[1]),
                best_10x10_compromise=dict(genome=best_joint[0].tolist(), **best_joint[1]),
            )
            (cfg.output_dir / "best_live_coarse.json").write_text(
                json.dumps(payload, indent=2), encoding="utf-8")
        if bar is not None:
            live_postfix(bar)
        return result

    islands: list[Island] = []
    with tqdm(total=cfg.islands*cfg.population, desc="Initial BEM", unit="candidate") as bar:
        for island_id, style in enumerate(STYLES[:cfg.islands]):
            rng = np.random.default_rng(int(master.integers(0, 2**32-1)))
            population: list[Individual] = []
            for name, x in seeds:
                if len(population) == cfg.population:
                    break
                x = repair(x)
                population.append(Individual(x, coarse(x, bar), island_id, 0, name))
                bar.update()
            while len(population) < cfg.population:
                seed = seeds[int(rng.integers(len(seeds)))][1]
                x = repair(seed + rng.normal(0.0, style.initial_sigma*(HIGH-LOW)))
                population.append(Individual(x, coarse(x, bar), island_id, 0, "initial"))
                bar.update()
            rank_and_crowding(population)
            islands.append(Island(style, rng, population))

    all_initial = [x for island in islands for x in island.population]
    if not any(x.valid for x in all_initial):
        reasons = sorted({x.result["reason"] for x in all_initial})
        raise RuntimeError("No valid initial geometry: " + repr(reasons[:20]))

    archive: list[Individual] = []
    history: list[dict[str, Any]] = []

    def update_archive(new: list[Individual]) -> None:
        nonlocal archive
        unique = {tuple(np.round(i.genome, 12)): i.copy() for i in archive+new if i.valid}
        pool = list(unique.values())
        if not pool:
            archive = []
            return
        archive = [pool[k].copy() for k in rank_and_crowding(pool)[0]]
        archive.sort(key=lambda i: -i.crowding)
        archive = archive[:512]

    def summary(generation: int) -> dict[str, Any]:
        valid = [x for island in islands for x in island.population if x.valid]
        z = min(valid, key=lambda i: i.result["dz_peak_m"])
        u = min(valid, key=lambda i: i.result["barrier_ev"])
        j = min(valid, key=lambda i: max(i.result["dz_peak_m"]/10e-6, i.result["barrier_ev"]/10e-3))
        return dict(generation=generation, valid=len(valid), archive=len(archive),
                    best_dz_um=z.result["dz_peak_m"]*1e6,
                    U_at_best_dz_mev=z.result["barrier_ev"]*1e3,
                    best_U_mev=u.result["barrier_ev"]*1e3,
                    dz_at_best_U_um=u.result["dz_peak_m"]*1e6,
                    compromise_dz_um=j.result["dz_peak_m"]*1e6,
                    compromise_U_mev=j.result["barrier_ev"]*1e3,
                    coarse_joint_hits=sum(i.result["dz_peak_m"] < cfg.dz_limit_m and
                                          i.result["barrier_ev"] < cfg.barrier_limit_ev for i in valid),
                    unique_evaluations=len(cache))

    update_archive(all_initial)
    history.append(summary(0)); print("G000", history[-1], flush=True)

    for generation in range(1, cfg.generations+1):
        following: list[Island] = []
        with tqdm(total=cfg.islands*cfg.offspring, desc=f"Generation {generation}", unit="candidate") as bar:
            for island_id, island in enumerate(islands):
                rank_and_crowding(island.population)
                children: list[Individual] = []
                while len(children) < cfg.offspring:
                    a = tournament(island.population, island.style, island.rng)
                    if island.rng.random() < .90:
                        b = tournament(island.population, island.style, island.rng)
                        alpha = island.rng.uniform(-.15, 1.15, N_GENES)
                        genome = repair(alpha*a.genome + (1.0-alpha)*b.genome)
                        origin = "crossover"
                    else:
                        genome = a.genome.copy()
                        origin = "clone"
                    genome = mutate(genome, island.style, island.rng, generation/cfg.generations)
                    children.append(Individual(genome, coarse(genome, bar), island_id,
                                               generation, origin))
                    bar.update()
                following.append(Island(island.style, island.rng,
                                        survive(island.population+children, cfg.population)))
        islands = following
        if cfg.migration_interval > 0 and generation % cfg.migration_interval == 0 and len(islands) > 1:
            sent = []
            for island in islands:
                rank_and_crowding(island.population)
                sent.append([i.copy() for i in sorted(island.population,
                            key=lambda i: (i.rank, -i.crowding, style_score(i, island.style)))[:cfg.migrants]])
            for source, migrants in enumerate(sent):
                destination = (source+1) % len(islands)
                target = islands[destination]
                islands[destination] = Island(target.style, target.rng,
                                              survive(target.population+migrants, cfg.population))
        update_archive([x for island in islands for x in island.population])
        history.append(summary(generation)); print(f"G{generation:03d}", history[-1], flush=True)
        save_csv(history, cfg.output_dir / "history.csv")
        save_csv([record(x) for x in archive], cfg.output_dir / "pareto_coarse.csv")
        if generation % cfg.checkpoint_interval == 0 or generation == cfg.generations:
            save_csv([record(x) for island in islands for x in island.population],
                     cfg.output_dir / f"population_gen_{generation:04d}.csv")

    if not archive:
        print("No archive candidates; inspect checkpoints.")
        return
    chosen = sorted(archive, key=lambda i: i.result["dz_peak_m"])[:cfg.fine_top]
    chosen += sorted(archive, key=lambda i: i.result["barrier_ev"])[:cfg.fine_top]
    chosen += sorted(archive, key=lambda i: max(i.objective))[:cfg.fine_top]
    unique = {tuple(np.round(i.genome, 12)): i for i in chosen}
    fine_rows: list[dict[str, Any]] = []
    for number, candidate in enumerate(tqdm(unique.values(), desc="Fine validation", unit="candidate"), 1):
        result, data = evaluate(candidate.genome, cfg, stage="fine", retain=True)
        row = dict(candidate=number, genome=candidate.genome.tolist(), **result)
        fine_rows.append(row)
        if data is not None:
            directory = cfg.output_dir / f"fine_{number:03d}"
            directory.mkdir(exist_ok=True)
            draw_fine(data, result, directory)
            (directory / "result.json").write_text(json.dumps(row, indent=2), encoding="utf-8")
    save_csv(fine_rows, cfg.output_dir / "fine_validation.csv")
    verified = [row for row in fine_rows if row["verified"]]
    (cfg.output_dir / "verified_hits.json").write_text(json.dumps(verified, indent=2), encoding="utf-8")
    print(f"Fine-verified joint hits: {len(verified)}; results: {cfg.output_dir}")


if __name__ == "__main__":
    main()
