"""Workflow 09: movable-x-knot, full-contour C4v open-centre island GA.

One common set of movable longitudinal knots defines both inner and outer RF
edges of one C4v fundamental arm. The four arms are generated by the existing
conventional X-junction template. Beyond the movable core lock point, offsets
are exactly zero and the geometry returns to the ordinary straight transport
cross. No central RF cross is added.

Optimization objectives are physical only: peak RF-null height deviation and
RF pseudopotential barrier. Geometry validity, rail width, endpoint attachment,
template slope restrictions and complete RF-null traces remain hard checks.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, PillowWriter
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle
from tqdm.auto import tqdm

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config.targets import RF_ANGULAR_FREQUENCY_RAD_S, TARGET_ION_HEIGHT_M
from core.analysis.barrier import compute_barrier_metrics, pseudopotential_profile_ev
from core.analysis.rf_null_trace import trace_rf_transverse_minimum
from core.ga.fixed_bem import FixedMeshBEM, available_backend
from core.geometry.manufacturability import check_x_junction_manufacturability
from core.geometry.mask_builder import build_geometry_aware_quadtree_x_junction_bem
from core.geometry.movable_knot_xjunction import (
    MovableKnotContour,
    build_movable_knot_parameters,
    fixed_knots_to_logits,
    softmax_gap_knots,
)

# Eight common intervals => nine knots, shared by inner and outer boundaries.
N_INTERVALS = 8
N_KNOTS = N_INTERVALS + 1
MIN_GAP_M = 3.0e-6
LOCK_MIN_M = 100e-6
LOCK_MAX_M = 180e-6
FIXED_CORE_KNOTS_M = np.array([0, 7, 15, 27, 43, 65, 92, 122, 150], dtype=float) * 1e-6

# Genome: gap logits | inner offsets at interior knots | outer offsets at interior knots | globals.
GAPS = slice(0, N_INTERVALS)
INNER = slice(GAPS.stop, GAPS.stop + N_KNOTS - 2)
OUTER = slice(INNER.stop, INNER.stop + N_KNOTS - 2)
LOCK = OUTER.stop
CENTER_IN = LOCK + 1
CENTER_OUT = LOCK + 2
START = LOCK + 3
LENGTH = LOCK + 4
POWER = LOCK + 5
BULGE = LOCK + 6
BULGE_CENTER = LOCK + 7
BULGE_WIDTH = LOCK + 8
N_GENES = LOCK + 9

LOW = np.array([-4.0]*N_INTERVALS + [-28e-6]*(N_KNOTS-2) + [-28e-6]*(N_KNOTS-2) +
               [LOCK_MIN_M, -50e-6, -8e-6, 8e-6, 60e-6, .70, -30e-6, 10e-6, 8e-6])
HIGH = np.array([4.0]*N_INTERVALS + [28e-6]*(N_KNOTS-2) + [28e-6]*(N_KNOTS-2) +
                [LOCK_MAX_M, -3e-6, 65e-6, 55e-6, 310e-6, 5.25, 30e-6, 140e-6, 80e-6])


@dataclass(frozen=True)
class Settings:
    backend: str
    islands: int
    population: int
    offspring: int
    generations: int
    migration_interval: int
    migrants: int
    retain_per_island: int
    seed: int
    coarse_points: int
    fine_points: int
    fine_top: int
    max_panels: int
    fast: bool
    animation_stride: int
    stall_generations: int
    burst_generations: int
    improvement_fraction: float
    burst_mutation_multiplier: float
    output_dir: Path
    rf_peak_v: float = 100.0
    target_z_m: float = TARGET_ION_HEIGHT_M
    dz_limit_m: float = 3e-6
    barrier_limit_ev: float = 1e-3
    lateral_limit_m: float = 5e-6
    rail_min_width_m: float = 18e-6


@dataclass(frozen=True)
class IslandStyle:
    name: str
    weights: tuple[float, float]
    explore: float
    final: float
    emphasis: str


STYLES = (
    IslandStyle("conventional_height", (7, 1), 1.00, .10, "inner"),
    IslandStyle("barrier_outer", (1, 7), 1.00, .10, "outer"),
    IslandStyle("balanced", (2, 2), .90, .09, "both"),
    IslandStyle("movable_x", (2, 2), 1.05, .10, "x"),
    IslandStyle("central", (3, 2), 1.05, .10, "central"),
    IslandStyle("inner_x_coupled", (4, 2), 1.10, .11, "inner_x"),
    IslandStyle("outer_x_coupled", (2, 4), 1.10, .11, "outer_x"),
    IslandStyle("wide", (2, 2), 1.25, .14, "wide"),
    IslandStyle("joint", (2, 2), .95, .08, "joint"),
    IslandStyle("diverse", (2, 2), 1.00, .10, "diverse"),
    IslandStyle("local", (2, 2), .42, .03, "local"),
    IslandStyle("taper", (2, 3), 1.00, .10, "global"),
)


@dataclass
class Individual:
    genome: np.ndarray
    result: dict[str, Any]
    island: int
    generation: int
    origin: str
    rank: int = 0
    crowding: float = 0.0

    @property
    def valid(self) -> bool:
        return bool(self.result["valid"])

    @property
    def objectives(self) -> np.ndarray:
        if not self.valid:
            return np.array([np.inf, np.inf])
        return np.array([self.result["dz_peak_m"]/3e-6, self.result["barrier_ev"]/1e-3])

    def copy(self):
        return Individual(self.genome.copy(), dict(self.result), self.island, self.generation,
                          self.origin, self.rank, self.crowding)


@dataclass
class Island:
    style: IslandStyle
    rng: np.random.Generator
    population: list[Individual]


class BEMField:
    def __init__(self, bem: FixedMeshBEM, charge: Any):
        self.bem, self.charge = bem, charge

    def electric_field(self, x_m: float, y_m: float, z_m: float):
        values = self.bem.field_batch(np.array([x_m]), np.array([y_m]), np.array([z_m]), self.charge)
        return tuple(map(float, self.bem.asnumpy(values)[0, 0]))


def repair(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=float).copy()
    if x.shape != (N_GENES,) or not np.all(np.isfinite(x)):
        raise ValueError(f"expected {N_GENES} finite genes")
    return np.clip(x, LOW, HIGH)


def decode(x: np.ndarray):
    x = repair(x)
    lock = float(x[LOCK])
    knots = softmax_gap_knots(x[GAPS], lock_m=lock, min_gap_m=MIN_GAP_M)
    inner = np.r_[0.0, x[INNER], 0.0]
    outer = np.r_[0.0, x[OUTER], 0.0]
    return knots, inner, outer


def baseline() -> np.ndarray:
    x = np.zeros(N_GENES)
    x[LOCK] = FIXED_CORE_KNOTS_M[-1]
    x[GAPS] = fixed_knots_to_logits(FIXED_CORE_KNOTS_M, min_gap_m=MIN_GAP_M)
    x[CENTER_IN:] = [-25e-6, 20e-6, 30e-6, 150e-6, 2.0, 0.0, 70e-6, 25e-6]
    return x


def conventional_cross() -> np.ndarray:
    """Exact conventional straight-cross seed: all movable contour offsets zero."""
    return baseline()


def seeds() -> list[tuple[str, np.ndarray]]:
    base = baseline()
    inner = base.copy(); inner[INNER] = np.array([-4, -8, -12, -12, -8, -4, -2], dtype=float)*1e-6
    outer = base.copy(); outer[OUTER] = np.array([2, 5, 9, 11, 8, 4, 2], dtype=float)*1e-6
    coupled = base.copy(); coupled[INNER] = np.array([-3, -7, -11, -13, -9, -5, -2], dtype=float)*1e-6
    coupled[OUTER] = np.array([2, 5, 10, 12, 8, 4, 1], dtype=float)*1e-6
    packed = base.copy(); packed[GAPS] = np.array([1.4, 1.0, .6, .1, -.3, -.7, -1.0, -1.2]); packed[LOCK] = 130e-6
    return [("conventional_exact", conventional_cross()), ("inner", inner), ("outer", outer),
            ("coupled", coupled), ("packed_x", packed)]


def parameters(x: np.ndarray):
    knots, inner, outer = decode(x)
    contour = MovableKnotContour(knots, inner, outer, lock_m=float(x[LOCK]), min_gap_m=MIN_GAP_M)
    return build_movable_knot_parameters(
        contour=contour, inner_edge_shift_at_centre_m=float(x[CENTER_IN]),
        outer_edge_shift_at_centre_m=float(x[CENTER_OUT]), rf_start_radius_override_m=float(x[START]),
        taper_length_m=float(x[LENGTH]), taper_power=float(x[POWER]),
        outer_bulge_amplitude_m=float(x[BULGE]), outer_bulge_center_m=float(x[BULGE_CENTER]),
        outer_bulge_sigma_m=float(x[BULGE_WIDTH]))


def rejected(reason: str, stage: str) -> dict[str, Any]:
    return dict(valid=False, verified=False, reason=reason, stage=stage, dz_peak_m=np.inf,
                dz_rms_m=np.inf, barrier_ev=np.inf, lateral_peak_m=np.inf, panels=0, points=0, converged=0)


def mesh(p: Any, fast: bool):
    if fast:
        return build_geometry_aware_quadtree_x_junction_bem(
            p, central_half_extent_m=145e-6, central_max_cell_m=46e-6,
            boundary_max_cell_m=17e-6, outer_max_cell_m=180e-6, min_cell_m=8e-6)
    return build_geometry_aware_quadtree_x_junction_bem(
        p, central_half_extent_m=180e-6, central_max_cell_m=30e-6,
        boundary_max_cell_m=10e-6, outer_max_cell_m=180e-6, min_cell_m=5e-6)


def evaluate(genome: np.ndarray, cfg: Settings, stage="coarse", retain=False):
    x = repair(genome)
    try:
        p = parameters(x)
        report = check_x_junction_manufacturability(p)
        if not report.valid:
            return rejected("geometry: "+"; ".join(map(str, report.messages)), stage), None
        s = np.linspace(0, p.arm_length_m, 2001)
        rin, rout = p.rail_boundaries_m(s)
        if np.min(rin) <= .5e-6:
            return rejected("inner clearance", stage), None
        if np.min(rout-rin) < cfg.rail_min_width_m:
            return rejected("rail width", stage), None
        model = mesh(p, cfg.fast and stage=="coarse")
        if model.n_panels > cfg.max_panels:
            return rejected("panel limit", stage), None
        bem = FixedMeshBEM(model.bem.panels_m, backend=cfg.backend)
        bem.assemble(block_rows=64); bem.factorize(); bem.release_matrix()
        charge = bem.solve_masks(model.bem.electrode_voltages_v); field = BEMField(bem, charge)
        n = cfg.fine_points if stage=="fine" else cfg.coarse_points
        trace = trace_rf_transverse_minimum(field, np.linspace(-350e-6,350e-6,n), initial_y_m=0.,
                                             initial_z_m=cfg.target_z_m, residual_tolerance_v_m=1e-3,
                                             max_transverse_shift_m=25e-6)
        converged = np.asarray(trace.converged, bool); z, y = np.asarray(trace.z_m,float), np.asarray(trace.y_m,float)
        if not trace.valid or converged.shape!=(n,) or not np.all(converged):
            return rejected("incomplete trace", stage), None
        if not np.all(np.isfinite(z)) or not np.all(np.isfinite(y)):
            return rejected("nonfinite trace", stage), None
        pseudo = np.asarray(pseudopotential_profile_ev(field,trace,rf_voltage_peak_v=cfg.rf_peak_v,
                          rf_angular_frequency_rad_s=RF_ANGULAR_FREQUENCY_RAD_S),float)
        barrier = compute_barrier_metrics(pseudo,trace)
        if not barrier.valid or pseudo.shape!=(n,) or not np.all(np.isfinite(pseudo)):
            return rejected("invalid pseudopotential", stage), None
        dz = z-cfg.target_z_m; peak=float(np.max(np.abs(dz))); rms=float(np.sqrt(np.mean(dz**2)))
        lateral,U=float(np.max(np.abs(y))),float(barrier.barrier_height_ev)
        if not np.all(np.isfinite([peak,rms,lateral,U])):
            return rejected("nonfinite metrics", stage), None
        return dict(valid=True,verified=bool(stage=="fine" and peak<cfg.dz_limit_m and U<cfg.barrier_limit_ev and lateral<cfg.lateral_limit_m),
                    reason="ok",stage=stage,backend=bem.backend_name,dz_peak_m=peak,dz_rms_m=rms,barrier_ev=U,
                    lateral_peak_m=lateral,barrier_reference_ev=float(barrier.reference_energy_ev),panels=int(model.n_panels),
                    points=n,converged=int(np.sum(converged))), (model,trace,pseudo) if retain else None
    except Exception as err:
        if cfg.backend=="cuda" and "out of memory" in str(err).lower():
            raise RuntimeError("CUDA OOM: reduce --max-panels or use --fast") from err
        return rejected(f"geometry/BEM error: {type(err).__name__}: {str(err).replace(chr(10),' ').strip()}", stage), None


def dominates(a: Individual,b: Individual) -> bool:
    if a.valid!=b.valid: return a.valid
    return bool(a.valid and np.all(a.objectives<=b.objectives) and np.any(a.objectives<b.objectives))


def rank_and_crowding(pop: list[Individual]) -> list[list[int]]:
    n=len(pop); defeated=[[] for _ in pop]; loss=np.zeros(n,int); fronts=[[]]
    for i in range(n):
        for j in range(i+1,n):
            if dominates(pop[i],pop[j]): defeated[i].append(j); loss[j]+=1
            elif dominates(pop[j],pop[i]): defeated[j].append(i); loss[i]+=1
    fronts[0]=[i for i in range(n) if loss[i]==0]
    while fronts[-1]:
        nxt=[]
        for i in fronts[-1]:
            for j in defeated[i]:
                loss[j]-=1
                if loss[j]==0:nxt.append(j)
        fronts.append(nxt)
    fronts.pop()
    for level,front in enumerate(fronts):
        for i in front:pop[i].rank,pop[i].crowding=level,0.
        valid=[i for i in front if pop[i].valid]
        if len(valid)<=2:
            for i in valid:pop[i].crowding=np.inf
            continue
        for axis in range(2):
            order=sorted(valid,key=lambda i:pop[i].objectives[axis]); lo,hi=pop[order[0]].objectives[axis],pop[order[-1]].objectives[axis]
            if hi<=lo:continue
            pop[order[0]].crowding=pop[order[-1]].crowding=np.inf
            for k in range(1,len(order)-1):
                if np.isfinite(pop[order[k]].crowding):pop[order[k]].crowding+=(pop[order[k+1]].objectives[axis]-pop[order[k-1]].objectives[axis])/(hi-lo)
    return fronts


def survivors(pool: list[Individual],size:int)->list[Individual]:
    result=[]
    for front in rank_and_crowding(pool):
        front.sort(key=lambda i:pool[i].crowding,reverse=True); result.extend(pool[i].copy() for i in front[:size-len(result)])
        if len(result)==size:break
    return result


def score(i: Individual,style:IslandStyle)->float:
    if not i.valid:return np.inf
    if style.emphasis=="joint":return max(i.result["dz_peak_m"]/10e-6,i.result["barrier_ev"]/10e-3)
    return float(np.dot(np.asarray(style.weights),i.objectives))


def tournament(pop:list[Individual],style:IslandStyle,rng:np.random.Generator)->Individual:
    a,b=(pop[int(k)] for k in rng.integers(0,len(pop),2))
    if rng.random()<.5:return a if score(a,style)<score(b,style) else b
    if a.rank!=b.rank:return a if a.rank<b.rank else b
    if a.crowding!=b.crowding:return a if a.crowding>b.crowding else b
    return a if score(a,style)<score(b,style) else b


def anneal(style:IslandStyle,f:float)->float:
    if f<=.75:return style.explore
    q=(f-.75)/.25
    return style.final+.5*(style.explore-style.final)*(1+math.cos(math.pi*q))


def sigmas(style:IslandStyle,fraction:float)->np.ndarray:
    scale=anneal(style,fraction); v=np.zeros(N_GENES)
    v[GAPS]=.34*scale; v[INNER]=8e-6*scale; v[OUTER]=8e-6*scale
    v[LOCK]=22e-6*scale; v[CENTER_IN:CENTER_OUT+1]=9e-6*scale; v[START]=10e-6*scale
    v[LENGTH]=24e-6*scale; v[POWER]=.35*scale; v[BULGE]=10e-6*scale; v[BULGE_CENTER]=18e-6*scale; v[BULGE_WIDTH]=12e-6*scale
    if style.emphasis=="inner":v[INNER]*=1.8
    elif style.emphasis=="outer":v[OUTER]*=1.8
    elif style.emphasis=="x":v[GAPS]*=2.3;v[LOCK]*=1.7
    elif style.emphasis=="inner_x":v[INNER]*=1.7;v[GAPS]*=1.5
    elif style.emphasis=="outer_x":v[OUTER]*=1.7;v[GAPS]*=1.5
    elif style.emphasis=="central":v[CENTER_IN:START+1]*=2.0
    elif style.emphasis=="wide":v*=1.35
    elif style.emphasis=="local":v*=.55
    return v


def mutate(
    parent: np.ndarray,
    style: IslandStyle,
    rng: np.random.Generator,
    fraction: float,
    burst: bool = False,
    burst_mutation_multiplier: float = 1.0,
) -> np.ndarray:
    x = parent.copy()

    sigma = sigmas(style, fraction)
    if burst:
        sigma *= burst_mutation_multiplier

    chance = np.full(N_GENES, 0.55)

    if style.emphasis in ("x", "inner_x", "outer_x"):
        chance[GAPS] = 0.88

    if style.emphasis == "inner":
        chance[INNER] = 0.88

    if style.emphasis == "outer":
        chance[OUTER] = 0.88

    if burst:
        chance = np.maximum(chance, 0.82)
        chance[GAPS] = 0.92
        chance[INNER] = 0.88
        chance[OUTER] = 0.88
        chance[LOCK] = 0.92
        chance[CENTER_IN:CENTER_OUT + 1] = 0.90
        chance[START:LENGTH + 1] = 0.85

    active = rng.random(N_GENES) < chance

    x[active] += rng.normal(
        0.0,
        sigma[active],
    )

    return repair(x)


def block_crossover(a:np.ndarray,b:np.ndarray,rng:np.random.Generator)->np.ndarray:
    out=np.empty(N_GENES)
    for block in (GAPS,INNER,OUTER,slice(LOCK,N_GENES)):
        alpha=rng.uniform(-.10,1.10);out[block]=alpha*a[block]+(1-alpha)*b[block]
    return repair(out)


def serialize(i:Individual)->dict[str,Any]:
    knots,inner,outer=decode(i.genome)
    return dict(island=i.island,generation=i.generation,origin=i.origin,rank=i.rank,crowding=i.crowding,
                genome=i.genome.tolist(),movable_knots_m=knots.tolist(),inner_offsets_m=inner.tolist(),outer_offsets_m=outer.tolist(),lock_m=float(i.genome[LOCK]),**i.result)


def save_csv(rows:list[dict[str,Any]],path:Path)->None:
    path.parent.mkdir(parents=True,exist_ok=True)
    if not rows:path.write_text("",encoding="utf-8");return
    keys=sorted(set().union(*(row.keys() for row in rows)))
    with path.open("w",newline="",encoding="utf-8") as fp:
        writer=csv.DictWriter(fp,fieldnames=keys,extrasaction="ignore");writer.writeheader()
        for row in rows:writer.writerow({k:json.dumps(v,allow_nan=True) if isinstance(v,(list,dict)) else v for k,v in row.items()})


def elite_rows(islands:list[Island],cfg:Settings)->list[dict[str,Any]]:
    rows=[]
    for isl in islands:
        rank_and_crowding(isl.population);best=sorted(isl.population,key=lambda i:(i.rank,-i.crowding,score(i,isl.style)))[:cfg.retain_per_island]
        rows.extend(serialize(i) for i in best)
    return rows


def draw_geometry(ax,row:dict[str,Any],label:str)->None:
    genome=repair(np.asarray(json.loads(row["genome"]) if isinstance(row["genome"],str) else row["genome"],float)); p=parameters(genome)
    s=np.linspace(0,260e-6,900);rin,rout=p.rail_boundaries_m(s)
    for theta in (0.,np.pi/2,np.pi,3*np.pi/2):
        c,q=np.cos(theta),np.sin(theta);x1,y1=s*c-rin*q,s*q+rin*c;x2,y2=s*c-rout*q,s*q+rout*c
        ax.fill(np.r_[x1,x2[::-1]]*1e6,np.r_[y1,y2[::-1]]*1e6,color="#db4f4f",ec="black",lw=.35,alpha=.90)
    knots,_,_=decode(genome); ki,ko=p.rail_boundaries_m(knots);ax.plot(knots*1e6,ki*1e6,"ko",ms=2.5);ax.plot(knots*1e6,ko*1e6,"wo",mec="black",ms=2.5)
    ax.axhline(0,color=".7",lw=.35);ax.axvline(0,color=".7",lw=.35);ax.set(xlim=(-260,260),ylim=(-260,260),aspect="equal");ax.set_xticks([]);ax.set_yticks([])
    ax.set_title(f"{label}\ndz={float(row['dz_peak_m'])*1e6:.2f} um, U={float(row['barrier_ev'])*1e3:.2f} meV\nlock={float(row['lock_m'])*1e6:.0f} um",fontsize=8)


def animate_surfaces(cfg:Settings)->None:
    try:import pandas as pd
    except ImportError:print("GIF skipped: pandas required.");return
    files=sorted((cfg.output_dir/"island_elites").glob("elites_gen_*.csv"))[::max(1,cfg.animation_stride)]
    if not files:return
    frames=[(int(f.stem.rsplit("_",1)[-1]),pd.read_csv(f)) for f in files];target=cfg.output_dir/"surface_animations";target.mkdir(exist_ok=True)
    for iid in range(cfg.islands):
        choices=[(g,t[(t["island"]==iid)&(t["valid"]==True)].sort_values(["rank","crowding","dz_peak_m","barrier_ev"],ascending=[True,False,True,True]).head(5)) for g,t in frames]
        if not any(not table.empty for _,table in choices):continue
        fig,axes=plt.subplots(1,5,figsize=(21,4.8),constrained_layout=True)
        def update(k):
            generation,table=choices[k]
            for ax in axes:ax.clear()
            rows=table.to_dict("records")
            for j,ax in enumerate(axes):
                if j<len(rows):
                    try:draw_geometry(ax,rows[j],f"Top {j+1}")
                    except Exception as err:ax.text(.5,.5,f"draw error\n{type(err).__name__}",transform=ax.transAxes,ha="center",va="center")
                else:ax.text(.5,.5,"no valid elite",transform=ax.transAxes,ha="center",va="center");ax.set_axis_off()
            fig.suptitle(f"Island {iid}: top-5 movable-knot RF surfaces — generation {generation}",fontsize=13);return axes
        anim=FuncAnimation(fig,update,frames=len(choices),interval=650,blit=False,repeat=True)
        try:anim.save(target/f"island_{iid:02d}_top5_surfaces.gif",writer=PillowWriter(fps=2),dpi=115)
        except Exception as err:print(f"GIF skipped island {iid}: {type(err).__name__}: {err}")
        plt.close(fig)


def fine_plots(data,result,directory:Path,title:str)->None:
    model,trace,pseudo=data;panels=np.asarray(model.bem.panels_m);rf=np.asarray(model.bem.electrode_voltages_v)>.5
    rects=[Rectangle((p[0]*1e6,p[2]*1e6),(p[1]-p[0])*1e6,(p[3]-p[2])*1e6) for p in panels]
    fig,ax=plt.subplots(figsize=(7,7));coll=PatchCollection(rects,array=rf.astype(float),cmap="RdYlBu_r");ax.add_collection(coll);ax.plot(np.asarray(trace.x_m)*1e6,np.asarray(trace.y_m)*1e6,"k-",lw=1.2);ax.set(xlim=(-230,230),ylim=(-230,230),aspect="equal",title=title,xlabel="x [um]",ylabel="y [um]");fig.colorbar(coll,ax=ax);fig.tight_layout();fig.savefig(directory/"layout.png",dpi=170);plt.close(fig)
    xx=np.asarray(trace.x_m)*1e6;fig,axs=plt.subplots(3,1,sharex=True,figsize=(9,9));axs[0].plot(xx,(np.asarray(trace.z_m)-TARGET_ION_HEIGHT_M)*1e6);axs[0].axhline(3,color="r",ls="--");axs[0].axhline(-3,color="r",ls="--");axs[0].set_ylabel("z-target [um]");axs[1].plot(xx,(pseudo-result["barrier_reference_ev"])*1e3);axs[1].axhline(1,color="r",ls="--");axs[1].set_ylabel("RF pseudo-ref [meV]");axs[2].plot(xx,np.asarray(trace.y_m)*1e6);axs[2].set(xlabel="x [um]",ylabel="y [um]");[a.grid(alpha=.25) for a in axs];fig.tight_layout();fig.savefig(directory/"profiles.png",dpi=170);plt.close(fig)


def parser():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument("--backend",choices=("auto","cuda","cpu"),default="auto");p.add_argument("--islands",type=int,default=12);p.add_argument("--population",type=int,default=100);p.add_argument("--offspring",type=int,default=25);p.add_argument("--generations",type=int,default=10);p.add_argument("--migration-interval",type=int,default=2);p.add_argument("--migrants",type=int,default=5);p.add_argument("--retain-per-island",type=int,default=5);p.add_argument("--coarse-points",type=int,default=61);p.add_argument("--fine-points",type=int,default=181);p.add_argument("--fine-top",type=int,default=25);p.add_argument("--max-panels",type=int,default=7000);p.add_argument("--fast",action="store_true");p.add_argument("--animation-stride",type=int,default=1);p.add_argument("--seed",type=int,default=20260926);p.add_argument("--output-dir",type=Path,default=Path("reports/09_movable_knot_full_genome"));
    p.add_argument(
        "--stall-generations",
        type=int,
        default=3,
        help="Enable exploration burst after this many generations without joint improvement.",
    )

    p.add_argument(
        "--burst-generations",
        type=int,
        default=2,
        help="Number of generations for each temporary exploration burst.",
    )

    p.add_argument(
        "--improvement-fraction",
        type=float,
        default=0.01,
        help="Required relative decrease of joint score to reset stagnation.",
    )

    p.add_argument(
        "--burst-mutation-multiplier",
        type=float,
        default=2.5,
        help="Multiplier for mutation amplitudes during a stagnation burst.",
    )
    
    return p


def main()->None:
    a=parser().parse_args();backend=available_backend(a.backend)
    if not backend.available:raise RuntimeError(backend.reason)
    if not 1<=a.islands<=len(STYLES):raise ValueError(f"islands must be 1..{len(STYLES)}")
    if a.population<8 or a.offspring<1 or a.generations<1:raise ValueError("population>=8, offspring/generations>=1")
    cfg = Settings(
        backend.selected,
        a.islands,
        a.population,
        a.offspring,
        a.generations,
        a.migration_interval,
        a.migrants,
        a.retain_per_island,
        a.seed,
        a.coarse_points,
        a.fine_points,
        a.fine_top,
        a.max_panels,
        a.fast,
        a.animation_stride,
        a.stall_generations,
        a.burst_generations,
        a.improvement_fraction,
        a.burst_mutation_multiplier,
        a.output_dir,
    )
    
    cfg.output_dir.mkdir(parents=True,exist_ok=True)
    (cfg.output_dir/"settings.json").write_text(json.dumps(dict(settings=asdict(cfg),backend=backend.as_dict(),genome_genes=N_GENES,n_knots=N_KNOTS,min_gap_m=MIN_GAP_M,physical_objectives=["dz","barrier"]),indent=2,default=str),encoding="utf-8")
    print("Workflow 09 movable-knot conventional C4v island GA | backend:",backend.selected,"| device:",backend.device_name)
    print(f"Genome={N_GENES}: {N_INTERVALS} movable x-gap logits, {N_KNOTS-2}+{N_KNOTS-2} edge offsets, 9 globals.")
    print("Island 0 includes an exact conventional straight-cross seed. Pareto objectives: dz and RF barrier.")
    master=np.random.default_rng(a.seed);seed_list=seeds();cache={};best_z=best_u=best_joint=None
    def joint(r):return max(r["dz_peak_m"]/10e-6,r["barrier_ev"]/10e-3)
    def coarse(x,bar=None):
        nonlocal best_z,best_u,best_joint
        x=repair(x);key=tuple(np.round(x,12))
        if key not in cache:cache[key],_=evaluate(x,cfg)
        r=dict(cache[key])
        if r["valid"]:
            if best_z is None or r["dz_peak_m"]<best_z[1]["dz_peak_m"]:best_z=(x.copy(),r.copy())
            if best_u is None or r["barrier_ev"]<best_u[1]["barrier_ev"]:best_u=(x.copy(),r.copy())
            if best_joint is None or joint(r)<joint(best_joint[1]):best_joint=(x.copy(),r.copy())
            (cfg.output_dir/"best_live_coarse.json").write_text(json.dumps(dict(best_dz=dict(genome=best_z[0].tolist(),**best_z[1]),best_barrier=dict(genome=best_u[0].tolist(),**best_u[1]),best_joint=dict(genome=best_joint[0].tolist(),**best_joint[1])),indent=2),encoding="utf-8")
        if bar is not None:
            if best_z is None:bar.set_postfix_str("valid=0",refresh=False)
            else:bar.set_postfix(dict(dz=f'{best_z[1]["dz_peak_m"]*1e6:.2f}um/U{best_z[1]["barrier_ev"]*1e3:.1f}',U=f'{best_u[1]["barrier_ev"]*1e3:.2f}meV/dz{best_u[1]["dz_peak_m"]*1e6:.1f}',joint=f'dz{best_joint[1]["dz_peak_m"]*1e6:.2f}/U{best_joint[1]["barrier_ev"]*1e3:.2f}'),refresh=False)
        return r

    islands=[]
    with tqdm(total=cfg.islands*cfg.population,desc="Initial BEM",unit="candidate") as bar:
        for iid,style in enumerate(STYLES[:cfg.islands]):
            rng=np.random.default_rng(int(master.integers(0,2**32-1)));pop=[]
            # Island 0 has one exact conventional cross. All other seeds are unique perturbations.
            if iid==0:
                x=conventional_cross();pop.append(Individual(x,coarse(x,bar),iid,0,"conventional_exact"));bar.update()
            order=np.roll(np.arange(len(seed_list)),iid%len(seed_list))
            for index in order:
                if len(pop)>=cfg.population:break
                name,seed=seed_list[int(index)]
                perturb=rng.normal(0,(HIGH-LOW)*.012*style.explore);x=repair(seed+perturb)
                pop.append(Individual(x,coarse(x,bar),iid,0,f"seed_{name}_island_{iid}"));bar.update()
            while len(pop)<cfg.population:
                seed=seed_list[int(rng.integers(len(seed_list)))][1];x=repair(seed+rng.normal(0,(HIGH-LOW)*.035*style.explore))
                pop.append(Individual(x,coarse(x,bar),iid,0,"initial"));bar.update()
            rank_and_crowding(pop);islands.append(Island(style,rng,pop))
    if not any(i.valid for isl in islands for i in isl.population):
        reasons=Counter(i.result["reason"] for isl in islands for i in isl.population);raise RuntimeError("No valid initial geometry: "+repr(reasons.most_common(20)))

    archive=[];
    history=[];
    reject_rows=[]
    best_joint_seen = np.inf
    stall_count = 0
    burst_remaining = 0
    search_mode = "NORMAL"
    def update_archive(new):
        nonlocal archive
        pool=list({tuple(np.round(i.genome,12)):i.copy() for i in archive+new if i.valid}.values());archive=[] if not pool else [pool[k].copy() for k in rank_and_crowding(pool)[0]];archive.sort(key=lambda i:-i.crowding);archive[:]=archive[:1000]

    def current_best_joint_score() -> float:
        candidates = [
            item
            for island in islands
            for item in island.population
            if item.valid
        ]

        if not candidates:
            return np.inf

        return min(
            joint(item.result)
            for item in candidates
        )


    def summary(g):
        all_items=[i for isl in islands for i in isl.population];valid=[i for i in all_items if i.valid];z=min(valid,key=lambda i:i.result["dz_peak_m"]);u=min(valid,key=lambda i:i.result["barrier_ev"]);j=min(valid,key=lambda i:joint(i.result));rejects=Counter(i.result["reason"] for i in all_items if not i.valid)
        for reason,count in rejects.items():reject_rows.append(dict(generation=g,reason=reason,count=count))
        return dict(
                    generation=g,
                    mode=search_mode,
                    stall_count=stall_count,
                    burst_remaining=burst_remaining,
                    joint_score=current_best_joint_score(),
                    valid=len(valid),
                    invalid=len(all_items)-len(valid),
                    archive=len(archive),
                    best_dz_um=z.result["dz_peak_m"]*1e6,
                    U_at_best_dz_mev=z.result["barrier_ev"]*1e3,
                    best_U_mev=u.result["barrier_ev"]*1e3,
                    dz_at_best_U_um=u.result["dz_peak_m"]*1e6,
                    best_joint_dz_um=j.result["dz_peak_m"]*1e6,
                    best_joint_U_mev=j.result["barrier_ev"]*1e3,
                    unique_evaluations=len(cache),rejects="; ".join(f"{k}:{v}" for k,v in rejects.most_common(4))
                )
    update_archive([i for isl in islands for i in isl.population]);history.append(summary(0));save_csv(elite_rows(islands,cfg),cfg.output_dir/"island_elites"/"elites_gen_0000.csv");print("G000",history[-1],flush=True)



    for gen in range(1, cfg.generations + 1):
        burst_active = burst_remaining > 0
        search_mode = "BURST" if burst_active else "NORMAL"

        next_islands = []

        with tqdm(
            total=cfg.islands * cfg.offspring,
            desc=f"Generation {gen} [{search_mode}]",
            unit="candidate",
        ) as bar:

            for iid, isl in enumerate(islands):
                rank_and_crowding(isl.population)

                elite = sorted(
                    isl.population,
                    key=lambda item: (
                        item.rank,
                        -item.crowding,
                        score(item, isl.style),
                    ),
                )[:max(2, min(5, len(isl.population)))]

                children = []

                while len(children) < cfg.offspring:
                    u = isl.rng.random()

                    if not burst_active:
                        # NORMAL:
                        # 65% direct local mutations around top-1/top-2.
                        if u < 0.65:
                            parent = (
                                elite[0]
                                if len(elite) == 1
                                or isl.rng.random() < 0.80
                                else elite[1]
                            )

                            child = parent.genome.copy()

                            origin = (
                                "top1_direct_mutation"
                                if parent is elite[0]
                                else "top2_direct_mutation"
                            )

                        elif u < 0.90:
                            left = tournament(
                                isl.population,
                                isl.style,
                                isl.rng,
                            )
                            right = tournament(
                                isl.population,
                                isl.style,
                                isl.rng,
                            )

                            child = block_crossover(
                                left.genome,
                                right.genome,
                                isl.rng,
                            )

                            origin = "pareto_block_crossover"

                        else:
                            left = elite[
                                int(isl.rng.integers(len(elite)))
                            ]

                            right = isl.population[
                                int(
                                    isl.rng.integers(
                                        len(isl.population)
                                    )
                                )
                            ]

                            child = block_crossover(
                                left.genome,
                                right.genome,
                                isl.rng,
                            )

                            origin = "elite_random_crossover"

                    else:
                        # BURST:
                        # Reduce local exploitation; escape current basin.
                        if u < 0.25:
                            parent = elite[
                                int(
                                    isl.rng.integers(
                                        min(2, len(elite))
                                    )
                                )
                            ]

                            child = parent.genome.copy()
                            origin = "burst_elite_mutation"

                        elif u < 0.60:
                            left = tournament(
                                isl.population,
                                isl.style,
                                isl.rng,
                            )

                            right = tournament(
                                isl.population,
                                isl.style,
                                isl.rng,
                            )

                            child = block_crossover(
                                left.genome,
                                right.genome,
                                isl.rng,
                            )

                            origin = "burst_pareto_crossover"

                        elif u < 0.80:
                            # Cross current elite with another live basin.
                            left = elite[
                                int(
                                    isl.rng.integers(len(elite))
                                )
                            ]

                            right = isl.population[
                                int(
                                    isl.rng.integers(
                                        len(isl.population)
                                    )
                                )
                            ]

                            child = block_crossover(
                                left.genome,
                                right.genome,
                                isl.rng,
                            )

                            origin = "burst_elite_random"

                        else:
                            # Controlled restart around the exact
                            # conventional cross / current movable-knot baseline.
                            seed = conventional_cross()

                            child = repair(
                                seed
                                + isl.rng.normal(
                                    0.0,
                                    (HIGH - LOW) * 0.10,
                                )
                            )

                            origin = "burst_conventional_restart"

                    child = mutate(
                        child,
                        isl.style,
                        isl.rng,
                        gen / cfg.generations,
                        burst=burst_active,
                        burst_mutation_multiplier=cfg.burst_mutation_multiplier,
                    )

                    children.append(
                        Individual(
                            child,
                            coarse(child, bar),
                            iid,
                            gen,
                            origin,
                        )
                    )

                    bar.update()

                next_islands.append(
                    Island(
                        isl.style,
                        isl.rng,
                        survivors(
                            isl.population + children,
                            cfg.population,
                        ),
                    )
                )

        islands = next_islands
        # Normal search migrates on the selected interval.
        # Burst search migrates every generation and shares more candidates.
        migration_now = (
            len(islands) > 1
            and (
                burst_active
                or (
                    cfg.migration_interval > 0
                    and gen % cfg.migration_interval == 0
                )
            )
        )

        if migration_now:
            migrant_count = (
                min(12, cfg.population)
                if burst_active
                else min(cfg.migrants, cfg.population)
            )

            outgoing = []

            for isl in islands:
                rank_and_crowding(isl.population)

                selected_migrants = sorted(
                    isl.population,
                    key=lambda item: (
                        item.rank,
                        -item.crowding,
                        score(item, isl.style),
                    ),
                )[:migrant_count]

                outgoing.append(
                    [item.copy() for item in selected_migrants]
                )

            for source, migrants in enumerate(outgoing):
                destination = (source + 1) % len(islands)
                target = islands[destination]

                islands[destination] = Island(
                    target.style,
                    target.rng,
                    survivors(
                        target.population + migrants,
                        cfg.population,
                    ),
                )

        # Measure physical joint progress after selection and migration.
        joint_now = current_best_joint_score()

        improved = (
            joint_now
            < best_joint_seen
            * (1.0 - cfg.improvement_fraction)
        )

        if improved:
            best_joint_seen = joint_now
            stall_count = 0

            # A successful burst ends early; return to focused exploitation.
            if burst_active:
                burst_remaining = 0

        else:
            stall_count += 1

        # This burst generation has now been consumed.
        if burst_active and burst_remaining > 0:
            burst_remaining -= 1

        # Only normal generations can schedule the next burst.
        if (
            not burst_active
            and burst_remaining == 0
            and stall_count >= cfg.stall_generations
        ):
            burst_remaining = cfg.burst_generations
            stall_count = 0

            print(
                f"Stagnation burst scheduled: "
                f"{cfg.burst_generations} generation(s), "
                f"starting at G{gen + 1:03d}.",
                flush=True,
            )

        update_archive(
            [
                item
                for isl in islands
                for item in isl.population
            ]
        )

        history.append(summary(gen))

        print(
            f"G{gen:03d}",
            history[-1],
            flush=True,
        )

        save_csv(
            history,
            cfg.output_dir / "history.csv",
        )

        save_csv(
            reject_rows,
            cfg.output_dir / "rejection_summary.csv",
        )

        save_csv(
            elite_rows(islands, cfg),
            cfg.output_dir
            / "island_elites"
            / f"elites_gen_{gen:04d}.csv",
        )

        save_csv(
            [
                serialize(item)
                for isl in islands
                for item in isl.population
            ],
            cfg.output_dir / f"population_gen_{gen:04d}.csv",
        )

    animate_surfaces(cfg)
    selected=sorted(archive,key=lambda i:i.result["dz_peak_m"])[:cfg.fine_top]+sorted(archive,key=lambda i:i.result["barrier_ev"])[:cfg.fine_top]+sorted(archive,key=lambda i:joint(i.result))[:cfg.fine_top];selected=list({tuple(np.round(i.genome,12)):i for i in selected}.values())
    fine=[]
    for num,item in enumerate(tqdm(selected,desc="Fine validation",unit="candidate"),1):
        result,data=evaluate(item.genome,cfg,"fine",True);row=dict(candidate=num,**serialize(item),**{"fine_"+k:v for k,v in result.items()});fine.append(row)
        if data is not None:
            directory=cfg.output_dir/"fine"/f"candidate_{num:03d}";directory.mkdir(parents=True,exist_ok=True);fine_plots(data,result,directory,f"Fine candidate {num}");(directory/"full_candidate.json").write_text(json.dumps(row,indent=2),encoding="utf-8")
    save_csv(fine,cfg.output_dir/"fine_validation.csv");valid=[r for r in fine if r["fine_valid"]];strict=[r for r in valid if r["fine_verified"]];candidates=strict or valid;top5=sorted(candidates,key=lambda r:max(r["fine_dz_peak_m"]/3e-6,r["fine_barrier_ev"]/1e-3))[:5];(cfg.output_dir/"top5_lithography_candidates.json").write_text(json.dumps(top5,indent=2),encoding="utf-8");save_csv(top5,cfg.output_dir/"top5_lithography_candidates.csv");(cfg.output_dir/"verified_hits.json").write_text(json.dumps(strict,indent=2),encoding="utf-8");print(f"Fine verified hits: {len(strict)} | top-5 design records: {cfg.output_dir/'top5_lithography_candidates.json'}")


if __name__=="__main__":main()
