"""Numerical tolerances and default discretisation settings."""

from __future__ import annotations

BEM_ASSEMBLY_HEIGHT_M = 1e-9

BEM_DEFAULT_N_RF = 10
BEM_DEFAULT_N_ARM = 10
BEM_DEFAULT_N_EXT = 4
BEM_DEFAULT_N_CENTER = 4

FINITE_DIFFERENCE_STEP_M = 0.1e-6

RF_NULL_ROOT_TOL_V_M = 1e-5
RF_NULL_ROOT_XTOL_M = 1e-10
RF_NULL_MIN_HEIGHT_M = 5e-6
RF_NULL_MAX_HEIGHT_M = 300e-6

DEFAULT_PATH_STEP_M = 2e-6
DEFAULT_PATH_X_MIN_M = -400e-6
DEFAULT_PATH_X_MAX_M = 400e-6

MAX_NULL_STEP_M = 10e-6
MAX_NULL_TRANSVERSE_SHIFT_M = 20e-6