"""Engineering and physics targets for robust X-junction design."""

from __future__ import annotations

from config.physical_constants import TWO_PI

TARGET_ION_HEIGHT_M = 90e-6

RF_FREQUENCY_HZ = 20e6
RF_ANGULAR_FREQUENCY_RAD_S = TWO_PI * RF_FREQUENCY_HZ

MAX_RF_VOLTAGE_PEAK_V = 300.0
PREFERRED_RF_VOLTAGE_PEAK_V = 150.0

TARGET_RADIAL_FREQUENCY_HZ = 1.5e6
MIN_RADIAL_FREQUENCY_HZ = 1.0e6
MAX_RADIAL_FREQUENCY_HZ = 2.0e6

RF_NULL_HEIGHT_MIN_M = 50e-6
RF_NULL_HEIGHT_MAX_M = 200e-6

MAX_NOMINAL_NULL_HEIGHT_DEVIATION_M = 3e-6
MAX_ROBUST_NULL_HEIGHT_DEVIATION_M = 5e-6

TARGET_TRANSPORT_DISTANCE_M = 100e-6
TARGET_TRANSPORT_TIME_S = 10e-6
MAX_FINAL_POSITION_ERROR_M = 10e-9
MAX_FINAL_PHONON_NUMBER = 1e-3
MAX_FINAL_VELOCITY_M_S = 1e-4